import os
DEBUG=False

HOSTNAME="127.0.0.1"
PORT="3306"
USERNAME="root"
PASSWORD="qwert123"
DATABASE="wangran"

DB_URI="mysql+mysqldb://{}:{}@{}:{}/{}?charset=utf8".format(USERNAME,PASSWORD,HOSTNAME,PORT,DATABASE)


SQLALCHEMY_DATABASE_URI=DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS=False
SECRET_KEY=os.urandom(24)

CMS_USER_ID="qwerr"

MAIL_SERVER="smtp.qq.com"
MAIL_PORT="587"
MAIL_USE_TLS=True
MAIL_USERNAME="731637839@qq.com"
MAIL_PASSWORD="zzhfwvngujplbbij"
MAIL_DEFAULT_SENDER="731637839@qq.com"

UEDITOR_UPLOAD_TO_QINIU = True
UEDITOR_QINIU_ACCESS_KEY = "RGJIrhTPY74Wo4SZw8OTzSnxTvLIu6lbPzrTu2xr"
UEDITOR_QINIU_SECRET_KEY = "j6AbvPSo8tFsNu6Hwoh9X2wyFGHjUvNNswkUq00t"
UEDITOR_QINIU_BUCKET_NAME = "mybaobao"
UEDITOR_QINIU_DOMAIN = "http://zhiwei-world.com/"



PEG_PAGE=6