"""empty message

Revision ID: 696721b07507
Revises: 82b4ed150145
Create Date: 2019-03-16 16:30:57.778621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696721b07507'
down_revision = '82b4ed150145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banners', sa.Column('image_url', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banners', 'image_url')
    # ### end Alembic commands ###
