"""empty message

Revision ID: a20f10061159
Revises: c201a831dd65
Create Date: 2019-03-23 17:42:22.862139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a20f10061159'
down_revision = 'c201a831dd65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('comment', 'contnet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('contnet', mysql.TEXT(), nullable=False))
    op.drop_column('comment', 'content')
    # ### end Alembic commands ###
